# Generated by Django 5.0 on 2023-12-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_category_alter_expense_options_expense_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
